### ISSUE TITLE
schema validation not testing all files 

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/kraken-lib#611]
the [ansible task](https://github.com/samsung-cnct/k2/blob/8ca90292fa8ace57530fedf6d08ef781e2c2398c/ansible/roles/kraken.config/tasks/main.yaml#L49-L54) to validate the config file is not actually hitting every file we want it to.  I tried to get it to fail by inputting a type mismatch on a required field, and it got through. For reference, I input `["helm"]` into the `name` field for the nodeConfigs of defaultAwsEtcdNode.

**Comment by DStorck** [comment]
snippet from config.yaml that should have failed: 
```
nodeConfigs:
    - &defaultAwsEtcdNode
      name: defaultAwsEtcdNode
      kind: 2
      mounts:
        -
          device: sdf
          path: /var/lib/docker
          forceFormat: true
```

schema for awsNodeConfig.json is that kind should be `node`: 
```{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://judkins.house/apis/k2/v1/awsNodeConfig.json",
  "$$target": "awsNodeConfig.json",
  "title": "AWS Node Configuration",
  "description": "Describes node configuration, some of which is specific to AWS (e.g. [instance types](https://aws.amazon.com/ec2/instance-types/)).",

  "properties": {
    "name": {
      "description": "Name of node for use by k2.",
      "type": "string"
    },
    "kind": {
      "description": "Type of config this is.",
      "enum": [ "node" ],
      "type": "string"
    },
    "mounts": {
      "description": "Additional mounts made in the node.",
      "items": { "$ref": "awsNodeMountConfig.json" },
      "type": "array"
    },
   "providerConfig": {
      "$ref": "awsNodeProviderConfig.json"
    },
    "taints": {
      "description": "List of AWS taints to associate with the kubernetes node",
      "items": { "$ref": "kubeNodeTaint.json" },
      "type": "array"
    }
  },
  "required": [
    "name",
    "providerConfig"
  ],

  "type": "object"
}
```
@coffeepac is this enough of the config or do you want the entire thing? This seemed like the only relevant part.

**Comment by coffeepac** [comment]
that should be sufficient, thank you.

**Comment by coffeepac** [comment]
@notjames as you work to port this code, please see if you can avoid this bug in the next iteration (or at least identify where this bug is coming from)

**Comment by davidewatson** [comment]
Based on k2/713, I think it was a mistake to allow `additionalProperties` to default to true. The original design noted the potential for errors but chose to increase developer productivity and use CI to catch these errors. We either need to set `"additionalProperties": false`, or write said CI job.

This may or may not address (all) of the issue(s) observed in here.

**Comment by coffeepac** [comment]
should be addressed by the new project but we should verify once he's done.

**Comment by notjames** [comment]
I am still working on the validator tests, which are now completed, but two tests are failing and I'm trying to run down why since the validation for those tests do not fail when I run validation on those tests from command line.

Having taken a minor break from the test debugging, I decided to double-back on this last night and this morning to see if my validator has the same issue as the current prod script, and it does. Or in other words, changing "kind" to something other than what is allowed in the enum, the validator fails to catch the explicit error case.

One other thing to note. My validator uses a semantic version library which conforms to  spec v2.0.0 (https://github.com/blang/semver). It's failing our current config on kubeConfig.version, which is v1.6.6. The validator fails the version because of the "v" in the string. Removing "v" from the version string should be considered for our config generator in order to use the new validator.

**Comment by davidewatson** [comment]
I think this should be put back on the Backlog, or ToDo.

**Comment by coffeepac** [comment]
this should be something that gets fixed in the schema itself and not the validation of it

**Comment by oneilcin** [comment]
My current understanding is that we will fix the NodeConfig schema validation check for the "kind" field.  Please clarify if this has a wider scope.

**Comment by oneilcin** [comment]
Used an online validator to test the kind field with our schema, the validation is working.  Will continue investigating complete validation using the jsonvalidator tool (so can use or schema refs), and the ansible - which is suspect

**Comment by oneilcin** [comment]
PR #906
