### ISSUE TITLE
jsonschema module throws exceptions

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/kraken-lib#623]
This should be fixed so it does not throw an exception, but only exits with an error code and a message.

As it is now, if a config file fails the schema validation, it crashes out and displays an exception which is barely readable in the ansible output.

This should produce a non-zero result code with some useful output which could be displayed by ansible as it fails gracefully.

**Comment by davidewatson** [comment]
An example schema validation error:

> TASK [kraken.config : Validate k2 configuration under schema] ********************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:     'whatWereYouThinkingDavid?'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_vzeMs6/ansible_module_jsonschema.py\", line 184, in <module>\n    main()\n  File \"/tmp/ansible_vzeMs6/ansible_module_jsonschema.py\", line 180, in main\n    module.fail_json(changed=False, msg=\"Validation failed\", result=result)\n  File \"/tmp/ansible_vzeMs6/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1993, in fail_json\n  File \"/tmp/ansible_vzeMs6/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1973, in _return_formatted\n  File \"/tmp/ansible_vzeMs6/ansible_modlib.zip/ansible/module_utils/basic.py\", line 414, in remove_values\n  File \"/tmp/ansible_vzeMs6/ansible_modlib.zip/ansible/module_utils/basic.py\", line 414, in <genexpr>\n  File \"/tmp/ansible_vzeMs6/ansible_modlib.zip/ansible/module_utils/basic.py\", line 414, in remove_values\n  File \"/tmp/ansible_vzeMs6/ansible_modlib.zip/ansible/module_utils/basic.py\", line 414, in <genexpr>\n  File \"/tmp/ansible_vzeMs6/ansible_modlib.zip/ansible/module_utils/basic.py\", line 425, in remove_values\nTypeError: Value of unknown type: <class 'jsonschema.exceptions.ValidationError'>, 'whatWereYouThinkingDavid?' is too long\n\nFailed validating u'maxLength' in schema['properties']['deployment'][u'properties'][u'clusters'][u'items'][u'properties'][u'name']:\n    {u'description': u'Name of this cluster.',\n     u'maxLength': 13,\n     u'minLength': 1,\n     u'type': u'string'}\n\nOn instance['deployment'][u'clusters'][0][u'name']:\n    'whatWereYouThinkingDavid?'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}

This code was intended to catch the exception.

```
    try:
        validator = ApiValidator(schema, schema_uri, subschema_dir)
        validator.validate(config)
    except (jsonschema.ValidationError, jsonschema.SchemaError) as e:
        result['is_valid'] = False
        result['exception'] = e
```

It's not because TypeError was thrown. Ideally, we would have a table mapping ValidationError exceptions to useful error messages.
