### ISSUE TITLE
BAC-102 ⁃ Run Kube-Bench as Part of Kraken-lib CI

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/kraken-lib#660]
We should add Kube-Bench to our K2 CI to evaluate for any security issues.  
(If we feel that Kube-Bench is adequate enough).

┆Attachments: <a href="https:&#x2F;&#x2F;samsung-cnct.atlassian.net&#x2F;secure&#x2F;attachment&#x2F;15103&#x2F;kube-bench-kraken-master-results.txt">kube-bench-kraken-master-results.txt</a>

**Comment by leahnp** [comment]
Can you explain what the difference between this ticket and https://github.com/samsung-cnct/k2/issues/647 is?

**Comment by leahnp** [comment]
Disregard above question...I see how it is different. Do we need to do #647 first, then this ticket?

**Comment by mikeln** [comment]
I don't think so...   checking our setup for security/best practices doesn't require it to be listed

**Comment by cwazy1** [comment]
➤ Patrick Christopher commented:

kube-bench:latest doesn't seem to be working.  it looks like they moved to a multi-stage build and things went poorly.  also not sure if they support k8s 1.9 yet.

**Comment by cwazy1** [comment]
➤ Patrick Christopher commented:

kube-bench is not in a great state right now, its build is broken, its only now getting dependency management and because it relies on CIS benchmarks, it doesn't support k8s 1.9 (https://www.cisecurity.org/benchmark/kubernetes/ only goes up to k8s 1.8).

we don't have CI for pre-1.9 versions of k8s right now so even if I added this it wouldn't do anything.  I'm going to push this back to 'ToDo' and unassign myself but for whoever gets this next, you'll need to determine:

  * how does kube-bench determine what version of k8s it is running against
  * what happens when kube-bench runs against a non-supported version of k8s (older or newer)?  
  * if kube-bench doesn't support the specific version, can we use the closest supported version?  is that sane?

**Comment by cwazy1** [comment]
➤ Alika Larsen commented:

After some initial research on the [Kubernetes CIS Benchmark](https://www.cisecurity.org/benchmark/kubernetes/)(v1.0.0, v1.1.0, v1.2.0) and experimenting with the [kube-bench](https://github.com/aquasecurity/kube-bench) tool it was discovered that:

  1. kube-bench must run on the node
  2. kubectl is required on the node

Answered Questions:
  * How does kube-bench determine what version of k8s it is running against?
    * [kube-bench uses and parses](https://github.com/aquasecurity/kube-bench/blob/850cde23e96df39024a74c6a44ea318b642fff3d/cmd/util.go#L216) the command kubectl version --short to determine what version of k8s the server is running

  * What happens when kube-bench runs against o non-supported version of k8s?
    * kube-bench will default to k8s 1.6 if it cannot determine the server version
    * but if it successfully detects a k8s version that is not supported (is 1.6, 1.7, 1.8) then it will [probably fail](https://github.com/aquasecurity/kube-bench/blob/850cde23e96df39024a74c6a44ea318b642fff3d/cmd/common.go#L67).

  * if kube-bench doesn't support the specific version, can we use the closest supported version?
    * because of how kube-bench works, I does seem sane to use the 1.8 set of kube-bench checks as a lot of the checking will still be relevant for a 1.9 k8s cluster.

**Comment by cwazy1** [comment]
➤ Alika Larsen commented:

Initial results of kube-bench on a Kraken master node:
{quote}24 checks PASS
42 checks FAIL
15 checks WARN{quote}
Initial results of kube-bench on a Kraken cluster node:
{quote}3 checks PASS
18 checks FAIL
2 checks WARN{quote}

Also attached full output of each kube-bench run to this issue.

Its also worth noting that modification of the kube-bench configuration files was necessary to successfully run kube-bench on a Kraken provisioned cluster. Most of this entailed telling kube-bench (via configuration) where Kraken things are located. Most notably that many things are specified in podspecs rather than config files. At some point we should evaluate the list of remediations produced by the kube-bench tool.

**Comment by cwazy1** [comment]
➤ Alika Larsen commented:

Based on the previous results here is the current design/implementation notes for kraken-lib:

  * hack/benchmark-test.sh
    * script to be run on node

  * build-scripts/benchmark-tests
    * script to be run on ci
    * script design to control all the node tests

  * build-scripts/benchmark-conf/{1.6,1.7,1.8,1.9}
    * directory to contain kube-bench configs for the various versions of k8s
    * note: 1.6-1.8 are official, 1.9 is our best guess

  * modify .gitlab-ci.yml
    * add test-security stage
    * add test-security:benchmark job
      * k8s-minus-1
      * k8s-minus-2

**Comment by cwazy1** [comment]
➤ Alika Larsen commented:

Completed coding work, updated gitlab CI, and submitted [PR](https://github.com/samsung-cnct/kraken-lib/pull/1056). Next I need to verify the CI tasks invoked by the above PR are executing correctly and then work to get this PR merged back to master.

**Comment by cwazy1** [comment]
➤ Alika Larsen commented:

After [a CI fix](https://github.com/samsung-cnct/kraken-lib/pull/1056/commits/cb765a4aa31dda556c54a33d0d3d6ec26c49acbd) I was able to get a [successful run](https://git.cnct.io/common-tools/samsung-cnct_kraken-lib/-/jobs/8162) of the benchmark test on gitlab. Results of tests can be found [here](https://git.cnct.io/common-tools/samsung-cnct_kraken-lib/-/jobs/8162/artifacts/browse/build/tests/).
