### ISSUE TITLE
Automate calico compatibility issues

### ISSUE THREAD

**Issue by guineveresaenger** [samsung-cnct/kraken-lib#907]
As per #901 there is an official backwards incompatibility due to a dependency update for calico nodes.

Currently, we check for compatibility via a python script and error out of the playbook if an incompatibility is detected, instucting the user to manually update their congfiguration file.

This process should be automated.

**Comment by guineveresaenger** [comment]
Here is the official calico release update information, which contains a lead to a possible manual workaround:

https://docs.projectcalico.org/v2.6/releases/

@jandrake are there any customers that may be affected by the above possible version updates?

**Comment by davidewatson** [comment]
I originally read this ticket to mean that we should rewrite the user's configuration file without their consent. If the user could accept or reject suggested changes that would be useful.

Since the config file is (currently) both a user interface and the intended state, we would want to preserve the YAML anchors and aliases. That might be a bit more difficult.

A related idea which we discussed was that we should store the config file from every CI run along with the results so that we can validate arbitrary configs against those which have passed CI, and then make recommendations on that basis.
