### ISSUE TITLE
BAC-100 ⁃ 1.8 support for gke

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/kraken-lib#917]
in working through the weekly version ticket, i noticed that current kubernetes version on our gke-config.yaml is at 1.7.6.  Now that we have 1.8 support for aws, we should test our support for gke. Current supported version for gke as of today is 1.8.1, but check [here](https://cloud.google.com/container-engine/supported-versions) when finishing up this issue to get the most current.

**Comment by oneilcin** [comment]
I found by looking at the supported releases https://cloud.google.com/container-engine/supported-versions, and from the google-containers slack channel, that an upgrade supports version 1.8.1-gke.0.

I'm getting this error ```Failed to start node upgrade: Desired node version (1.8.1-gke.0) cannot be greater than current master version (1.7.6-gke.1)```

It looks like our ansible deploys a default container cluster first, and then tries to upgrade it to the specified version.  The default Master seems to be at 1.7.6-gke.1, so unless we change how we build the cluster will have to wait.  Note: a new cluster creation supports 1.8.1-gke.1.

**Comment by oneilcin** [comment]
Blocked until it is completely rolled out.  

Check releases and zones here: https://cloud.google.com/container-engine/release-notes
The release-notes are a bit confusing, I tried it in us-east1-c, and us-east1-b and it errors with ```Desired node version (1.8.1-gke.1) cannot be greater than current master version (1.7.8-gke.0)```

**Comment by davidewatson** [comment]
Seach for "Rollout schedule": https://cloud.google.com/container-engine/release-notes

**Comment by oneilcin** [comment]
hmmm, but if you scroll down to the Rollout Schedule for October 24, it looked like 1.8.1 should be available everywhere by end of October.

**Comment by guineveresaenger** [comment]
Accordign to the [release notes](https://cloud.google.com/kubernetes-engine/release-notes) as of 11/7 and the week thereafter k8s v1.8.2 is now available for _new_ clusters (1.8.x hadn't neen avaibale for new clusters before).

**Comment by cwazy1** [comment]
➤ Patrick Christopher commented:

This is a fairly major CI blocker now.  GKE cluster up jobs take \~45 minutes to run instead of 3.

**Comment by cwazy1** [comment]
➤ Guinevere Saenger  commented:

CI running currently.

**Comment by cwazy1** [comment]
➤ Guinevere Saenger  commented:

For some reason, CI spins up a 1.7.11 master.

**Comment by cwazy1** [comment]
➤ David Watson commented:

Why not make the version field optional for gke and then, if it is not present, accept the default. Then we will never have to think about this again.

The upgrade code is what makes CI slow: [https://github.com/samsung-cnct/kraken-lib/blob/master/ansible/roles/kraken.provider/kraken.provider.gke/tasks/update-cluster.yaml](https://github.com/samsung-cnct/kraken-lib/blob/master/ansible/roles/kraken.provider/kraken.provider.gke/tasks/update-cluster.yaml) Notice how we skip the upgrade step if kubeVersion is not defined. So we can either change the schema to make the version in kubeConfig not required (which is not great because AWS really does require it), or just specify the version as the empty string in the default gke config and update kraken.provider.gke to also skip upgrades if the kubeVersion is the empty string.

**Comment by cwazy1** [comment]
➤ Guinevere Saenger  commented:

This does not make me happy from a customer perspective. Right now, if I'm a customer and want to specify a 1.8 cluster on gke, I can't seemingly do that with kraken, a case that CI is intended to catch, not bypass quietly.

**Comment by cwazy1** [comment]
➤ David Watson commented:

You can still specify a 1.8 cluster. It will just take 45 minutes to create. The whole point of this ticket is to avoid running CI on GKE cluster upgrades because it takes too long. GKE always starts with their defaults.

Alternatively, you can wait until Google finishes changing the default k8s version for our CI region.

I don't think we should invest much effort here. Maybe waiting is the least effort. In fact, it probably is.

**Comment by cwazy1** [comment]
➤ Guinevere Saenger  commented:

But it seems right now I cannot specify a 1.8 cluster. I'd like to know why.

**Comment by cwazy1** [comment]
➤ Guinevere Saenger  commented:

is it the CI region? Google claims there is support for all regions, unless i'm missing something.

**Comment by cwazy1** [comment]
➤ Guinevere Saenger  commented:

Attempted various cheats with passing no version or empty version. current default version for new GKE clusters is v1.7.11; can default to doing that to get CI run down. 
Attempting trying to pass v0.0.0 with extra condition to skip update task

**Comment by cwazy1** [comment]
➤ Guinevere Saenger  commented:

update: Fails because previous tasks require a valid k8s minor version

**Comment by cwazy1** [comment]
➤ Guinevere Saenger  commented:

update: Decided to simply use current golang default at v1.7.11 to get CI run down to \~4.30 minutes. Might put more work into this in the future.

**Comment by cwazy1** [comment]
➤ Guinevere Saenger  commented:

Passing all but e2e: [https://github.com/samsung-cnct/kraken-lib/pull/1055](https://github.com/samsung-cnct/kraken-lib/pull/1055)
