### ISSUE TITLE
Conform more completely to that which is tested upstream

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/kraken-lib#929]
Similar to https://github.com/samsung-cnct/kraken/issues/206 we should ensure other pieces conform to that which is tested upstream:

- [x] docker
- [x] cni
- [x] other?

**Comment by coffeepac** [comment]
this issue should cover:
- updating the weekly on-call issue to check for changes in specified dependent projects
- determining what the dependent projects are
- determining level of effort for creating versioned config values for all of the projects so our config file pivots correctly with minimal user effort

**Comment by guineveresaenger** [comment]
Regarding docker:
We get docker from coreos. We don't have control over which docker we get from coreos any given day. In order to ensure that our docker version conforms to tested standards, we need to pin an explicit version of docker via uri in the config file.
For reference in schema: https://github.com/samsung-cnct/kraken-lib/blob/master/schemas/config/v1/dockerContainerConfig.json#L25-L34

**Comment by guineveresaenger** [comment]
Thoughts so far:

Calico and weave do not get used in the kubernetes tests. Should we:
- a) use the versions of calico and weave as recommended by these projects
- b) use the kubernetes standard tool instead

Docker is being tested and passing with version 1.13.1. We should explicitly use that version in our config, as per comment above.

Fluentd is passing tests at v2.0.9. We should keep an eye on this for logging purposes (if not in kraken-lib itself).

Prometheus is at v0.2.2 in the tests. If we are to use Prometheus, as is being discussed currently, we should use that version.

Tests can be found [here:](https://k8s-gubernator.appspot.com/builds/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability-stable1)

**Comment by philoserf** [comment]
I went looking for how our fellow k8s cluster creation tools test e2e. I can't say I found a good solution that covers our use cases.

**Comment by guineveresaenger** [comment]
**Version comparisons of dependencies**
_These comparisons are based on passing upstream tests found [here](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-scalability/7761/artifacts/nodes.yaml)_

Docker
Tested: 1.13.1
Kraken: 1.12.6 (via CoreOS)
Latest: Docker CE v17.09.0 (which CoreOS is currently testing on alpha)

_TODO: file issue to pin docker explicitly in config file_

CoreOS:
Tested: n/a
Kraken: 1465.7.0
Latest: 1520.8.0

^^ Kubernetes upstream seems to be using docker version 1.13.1, which is not being further maintained. To avoid issues, we should pin docker explicitly, and follow Kubernetes' use.

Calico/cni
Tested: n/a; K8s doesn't use calico
Kraken: 1.10.0 (all versions)
Latest: 1.11.0

_TODO: file an issue on investigating kubenet which is being used by upstream kubernetes instead of calico/cni_

Calico/node
Tested: n/a
Kraken: 2.4.1 (k8s 1.6 of kraken); 2.6.1 default
Latest: 2.6.2

_TODO: make people aware of calico upgrade instructions from k8s 1.6 to 1.7+_

Weave
Tested: n/a
Kraken: 1.9.8
Latest: 2.0.5

^^ we also only used this for one customer ever
_TODO: make people aware of weave upgrade instructions from k8s 1.6 to 1.7+_

Flannel
Tested: n/a
Kraken: 0.8.0
Latest: 0.9.0

etcd
Tested: 3.0.17
Kraken: 3.0.17
Latest: 3.2.9

^^ this is really behind, that is interesting

_TODO: decide which of these dependencies should be tracked in weekly oncall, and update oncall instructions_

**Comment by guineveresaenger** [comment]
Invitation to comment:

- Should we also pin/oncall-update the coreOS version used in the config file? As it is, we are many versions behind. 

- Which of these dependencies do we want to update as part of weekly oncall?

- Are any dependencies missing from the writeup above?

- Should we update calico, flannel, weave, and coreOS to the lastest stable version? If so, should this be a subtask of weekly oncall? I'm a little wary of this, because it will add more manual work to that process, and can potentially introduce breaking changes.

**Comment by guineveresaenger** [comment]
@coffeepac can you elaborate on your above comment? 

> determining level of effort for creating versioned config values for all of the projects so our config file pivots correctly with minimal user effort

All the dependencies I looked at are from the config file, and have versions (excepting the docker is provided via coreOS, but that's just a layer of obfuscation.)

I don't know what we would be doing differently in terms of creating versioned config vaues? However, in https://github.com/samsung-cnct/kraken-lib/issues/907#issuecomment-343044274
there is some discussion on having a dependency matrix, which sounds complicated, interesting, and useful.

**Comment by coffeepac** [comment]
I was talking about having a dependency matrix and then having kraken choose which version of canal to use with a specified version of kubernetes.  my idea is that the user doesn't care, particularly, about what sub-component version they are using, they really care about which version of kubernetes they are using.

**Comment by guineveresaenger** [comment]
Issue for possible dependency matrix: https://github.com/samsung-cnct/kraken-lib/issues/953

**Comment by davidewatson** [comment]
I beg to differ on whether you have enough experience. But of course, I'd be happy to help if can.

**Comment by guineveresaenger** [comment]
ToReview:

- check comment for weekly on-call issue https://github.com/samsung-cnct/issues/issues/90#issuecomment-343349768

- check list of above dependencies for being complete

- make sure the following issues filed make sense
#946, #947, #952, #953

**Comment by philoserf** [comment]
an example of a kubernetes specific support matrix

https://github.com/kubernetes/client-go#compatibility-matrix

**Comment by guineveresaenger** [comment]
^^ I moved your comment to the related new issue.

**Comment by leahnp** [comment]
Hey @guineveresaenger great work with this!!!!

My only question is about the weekly on call ticket - is this ongoing work we need to add to the core issue or just additional work for this week?

**Comment by leahnp** [comment]
```
-Please check the following dependencies, and make sure they are in line with either the upstream repo, or with Kubernetes current test standards.
-After you've checked and updated dependencies, please incorporate dependency check procedures in the ticket for next week (i.e. add a new step to the list above)
```
The above bullet points need to be added to the weekly work.
